#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-PerlIO-via-Timeout
Version  : 0.32
Release  : 1
URL      : https://cpan.metacpan.org/authors/id/D/DA/DAMS/PerlIO-via-Timeout-0.32.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/D/DA/DAMS/PerlIO-via-Timeout-0.32.tar.gz
Source1  : http://http.debian.net/debian/pool/main/libp/libperlio-via-timeout-perl/libperlio-via-timeout-perl_0.32-1.debian.tar.xz
Summary  : 'a PerlIO layer that adds read & write timeout to a handle'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-PerlIO-via-Timeout-license
Requires: perl-PerlIO-via-Timeout-man
Requires: perl(Module::Build::Tiny)
Requires: perl(Test::SharedFork)
Requires: perl(Test::TCP)
BuildRequires : perl(Module::Build::Tiny)
BuildRequires : perl(Test::SharedFork)
BuildRequires : perl(Test::TCP)

%description
This archive contains the distribution PerlIO-via-Timeout,
version 0.32:
a PerlIO layer that adds read & write timeout to a handle

%package license
Summary: license components for the perl-PerlIO-via-Timeout package.
Group: Default

%description license
license components for the perl-PerlIO-via-Timeout package.


%package man
Summary: man components for the perl-PerlIO-via-Timeout package.
Group: Default

%description man
man components for the perl-PerlIO-via-Timeout package.


%prep
tar -xf %{SOURCE1}
cd ..
%setup -q -n PerlIO-via-Timeout-0.32
mkdir -p %{_topdir}/BUILD/PerlIO-via-Timeout-0.32/deblicense/
mv %{_topdir}/BUILD/debian/* %{_topdir}/BUILD/PerlIO-via-Timeout-0.32/deblicense/

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/perl-PerlIO-via-Timeout
cp LICENSE %{buildroot}/usr/share/doc/perl-PerlIO-via-Timeout/LICENSE
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/PerlIO/via/README.pod
/usr/lib/perl5/site_perl/5.26.1/PerlIO/via/Timeout.pm

%files license
%defattr(-,root,root,-)
/usr/share/doc/perl-PerlIO-via-Timeout/LICENSE

%files man
%defattr(-,root,root,-)
/usr/share/man/man3/PerlIO::via::Timeout.3
